#!/bin/sh

### BEGIN INIT INFO
# Provides:          virtualbox-SHORTNAME
# Required-Start:    $local_fs $remote_fs vboxdrv virtualbox
# Required-Stop:     $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: virtual machine "LONGNAME"
# Description:       VirtualBox virtual machine "LONGNAME"
### END INIT INFO

# If you are using Ubuntu <9.10, you might need to change "Default-Stop"
# above to "S 0 1 6".

DESC="VirtualBox virtual machine \"LONGNAME\""
NAME="virtualbox-SHORTNAME"
SCRIPTNAME="/etc/init.d/$NAME"

VM_OWNER="USERNAME"
VM_NAME="LONGNAME"  # must match registered name in VirtualBox

# command to start this VM
start_vm () {
  # if VirtualBox was compiled with VNC support:
  #
  # to use the built-in VNC, we have to use VBoxHeadless;
  # because it doesn't exit, we can't properly check for success this way,
  # so we might as well save the output with screen
  #sudo -H -u "$VM_OWNER" screen -dmS "$NAME" \
  #     "$HEADLESS_CMD" --startvm "$VM_NAME" --vrde=off -n
  #     # -m PORT -o 'PASSWORD'

  # otherwise:
  sudo -H -u "$VM_OWNER" "$MANAGE_CMD" startvm "$VM_NAME" -type vrdp \
       > /dev/null

}

. /etc/init.d/virtualbox-vm
